import React from "react"
import Navbar from "../../Components/Navbar"
import Footer from "../../Components/Footer"
// import greenpoint from "../../Images/greenpoient.jpg"
// import greenhand from "../../Images/greenpoints1.png"
import greenhand from "../../Images/Green-points-hand.jpg"
import imgfour from "../../Images/Four.png"
import imgfive from "../../Images/Five.png"
import { Link } from "react-router-dom"
import greenpoint from "../../Images/Redeem-your-green-points.jpg"
import SEO from "../../SEO"
import { useState } from "react"
import { useEffect } from "react"
import { Helmet } from "react-helmet"
import { createElement } from "react"

function Redeem(){

    // set title 
    // document.title = "Ecoil | Redeem Your Green Points"

    const { getTags } = SEO()
    // getTags("Home")
    const [tags, setTags] = useState([])

    useEffect(() => {
    //   console.log("tags", tags)
        getTags("Redeem Your Green Points").then(res => setTags(res))
    }, [])

    useEffect(() => {
      console.log("tags", tags)
    }, [tags])

    return(
        <div>
            <Navbar />

            <Helmet prioritizeSeoTags>
            {tags && tags.map((tag, index) =>                 
                  createElement(tag.tag_name, {...tag.a_json}, tag.content)
            )}
            </Helmet>

            <div className="Single-service-reedem" style={{backgroundImage: `linear-gradient(to right, rgb(8 0 0 / 42%), rgb(0 0 0 / 52%)), url(${greenpoint})`, backgroundPosition: 'center', backgrounSize: 'cover'}}>
                <div className="max-width">
                <div className="container">
                    <div className="row justify-content-center align-items-center">
                    <div className="col-lg-12">
                        <div className="contact-text">
                        <h1>Redeem Your Green Points</h1>
                        <p>
                            Ecoil collects used cooking oil from restaurants, canteens,
                            cloud kitchens, caterers and pays them handsomely. Ecoil also
                            rewards with GREEN POINTS which the restaurants and canteen
                            owners can redeem to buy some amazing goodies.
                        </p>
                        </div>
                    </div>
                    </div>
                </div>
                </div>
            </div>

            <div
                className="col-lg-12 text-center pt-5 pb-4"
                style={{ backgroundColor: "rgb(211, 247, 203)" }}
            >
                <p>
                <Link to="/dashboard" className="btn btn-service">
                    Redeem Your Green Points
                </Link>
                </p>
            </div>

            <section className="about-us-main py-lg-5 py-3">
                <div className="max-width">
                <div className="container">
                    <div className="row justify-content-center align-items-center">
                    <div className="col-lg-6 col-11 pb-3 d-lg-none d-md-block d-block">
                    <div className="about-right-img" style={{ textAlign: "center" }}>
                    <img src={greenhand} className="w-75" alt="image"  />
                        {/* <div className="background-div p-5" style={{ height: "auto" }}>
                            <img src={greenhand} className="w-100"  />
                        </div> */}
                        {/* <img src="img/greenpoientmain.jpg" class="about-right-img2" /> */}
                        {/* <div class="about-experience d-flex">
                            <div class="about-img">
                                <img src="img/t3.png" />
                            </div>
                            <div class="about-tesst">
                                <h4 class="mt-3 mb-0">3M kg</h4>
                                <p>UCO Converted Till Date</p>
                            </div>
                            </div> */}
                        </div>
                    </div>
                    <div className="col-lg-6 col-11 pb-3 pb-3">
                        <div className="about-heading">
                        {/* <span>ABOUT US</span> */}
                        <h4> What do you mean by carbon footprint and Green points? </h4>
                        <p className="text-justify">
                            A carbon footprint is the total amount of greenhouse gases
                            (including carbon dioxide and methane) that are generated by our
                            actions.
                            <br />
                            Restaurant owners can earn green points with every sale of used
                            cooking oil and can redeem them to buy some amazing things. So,
                            for every green point gain, you are reducing the carbon
                            footprint and ultimately saving the environment.
                        </p>
                        </div>
                        <div className="body-after d-lg-flex d-md-inline-block d-sm-inline-block d-inline-block">
                        <div className="about-btn py-4 text-center d-none d-md-none d-">
                            <button className="btn btn-about">More About Us</button>
                        </div>
                        {/* <div
                                class="ceo_name px-4 pt-4 d-lg-flex d-md-inline-block d-sm-inline-block d-inline-block"
                            >
                                <div class="img px-4">
                                <img src="img/07.jpg" class="text-center" />
                                </div>
                                <div class="title">
                                <h4 class="mb-0">Joe Hodgson</h4>
                                <p>CEO Wastco</p>
                                </div>
                            </div> */}
                        <div className="about-btn py-4 text-center d-none d-md-none ">
                            <button className="btn btn-about">More About Us</button>
                        </div>
                        </div>
                    </div>
                    <div className="col-lg-6 pb-3 d-lg-block d-md-none d-sm-none d-none">
                        <div className="about-right-img" style={{ textAlign: "center" }}>
                        <img src={greenhand} className="w-75" alt="image"  />
                        {/* <div className="background-div p-5" style={{ height: "auto" }}>
                            <img src={greenhand} className="w-50"  />
                        </div> */}
                        {/* <img src="img/greenpoientmain.jpg" class="about-right-img2" /> */}
                        {/* <div class="about-experience d-flex">
                            <div class="about-img">
                                <img src="img/t3.png" />
                            </div>
                            <div class="about-tesst">
                                <h4 class="mt-3 mb-0">3M kg</h4>
                                <p>UCO Converted Till Date</p>
                            </div>
                            </div> */}
                        </div>
                    </div>
                    </div>
                </div>
                </div>
            </section>

            <section className="container mt-5 mb-5">
                <div className="row justify-content-around">
                <div className="col-lg-5 bg-change">
                    <div className="information d-lg-flex align-item-center flex-lg-column">
                    <div className="pic">
                        <img src={imgfour} alt="" className="image-size-impact-page" style={{ margin: "auto"}} />
                    </div>
                    <div className="pic-text">
                        <h2 className="pic-heading">
                        {" "}
                        How Ecoil Helps In Reducing Carbon Footprint?{" "}
                        </h2>
                        <p className="pic-para">
                        Ecoil collects used cooking oil from various sources like
                        restaurants, snack making companies etc and facilitates its
                        conversion to biodiesel- a green fuel, hence reducing the carbon
                        footprint and protecting environment.
                        </p>
                    </div>
                    </div>
                </div>
                <div className="col-lg-5 bg-change">
                    <div className="information d-md-flex align-item-center flex-lg-column">
                    <div className="pic">
                        <img src={imgfive} alt="" className="image-size-impact-page" style={{ margin: "auto"}} />
                    </div>
                    <div className="pic-text">
                        <h2 className="pic-heading">
                        How can a restaurant contribute to saving carbon footprint and
                        thus generate green points?
                        </h2>
                        <p className="pic-para">
                        When any restaurant owner sells used cooking oil (UCO) to Ecoil,
                        they are rewarded with green points which in turn can be redeemed
                        to buy a variiety of products.These green points are generated for
                        carbon footprints saved by the conversion of Used cooking oil into
                        biodiesel by Ecoil
                        </p>
                    </div>
                    </div>
                </div>
                </div>
            </section>

            <Footer />
        </div>
    )
}

export default Redeem